REFERENCES = {
    "xxs": {
        "grid_ranks": 2,
        "real_tucker_ranks": [2, 40, 40, 40],
        "complex_tucker_ranks": [2, 30, 30, 30],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
    },
    "xs": {
        "grid_ranks": 2,
        "real_tucker_ranks": [3, 50, 50, 50],
        "complex_tucker_ranks": [3, 40, 40, 40],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
    },
    "small": {
        "grid_ranks": 4,
        "real_tucker_ranks": [3, 75, 75, 60],
        "complex_tucker_ranks": [3, 60, 60, 40],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 1,
    },
    "medium": {
        "grid_ranks": 8,
        "real_tucker_ranks": [3, 90, 90, 70],
        "complex_tucker_ranks": [3, 75, 75, 60],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 1,
    },
    "large": {
        "grid_ranks": 16,
        "real_tucker_ranks": [4, 100, 100, 100],
        "complex_tucker_ranks": [4, 80, 80, 80],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 1,
    },
    "xs2": {
        "grid_ranks": 2,
        "real_tucker_ranks": [3, 50, 50, 50],
        "complex_tucker_ranks": [3, 40, 40, 40],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 2,
    },
    "xs4": {
        "grid_ranks": 2,
        "real_tucker_ranks": [3, 50, 50, 50],
        "complex_tucker_ranks": [3, 40, 40, 40],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 4,
    },
    "xs8": {
        "grid_ranks": 2,
        "real_tucker_ranks": [3, 50, 50, 50],
        "complex_tucker_ranks": [3, 40, 40, 40],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 8,
    },
    "xxs1": {
        "grid_ranks": 2,
        "real_tucker_ranks": [2, 40, 40, 40],
        "complex_tucker_ranks": [2, 30, 30, 30],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 1,
    },
    "xxs2": {
        "grid_ranks": 2,
        "real_tucker_ranks": [2, 40, 40, 40],
        "complex_tucker_ranks": [2, 30, 30, 30],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 2,
    },
    "xxs4": {
        "grid_ranks": 2,
        "real_tucker_ranks": [2, 40, 40, 40],
        "complex_tucker_ranks": [2, 30, 30, 30],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 4,
    },
    "xxs4-noop": {
        "grid_ranks": 2,
        "real_tucker_ranks": [2, 40, 40, 40],
        "complex_tucker_ranks": [2, 30, 30, 30],
        "conv_hidden": 48,
        "operator_steps": 0,
        "op_hdim": 48,
        "num_segments": 4,
    },
    "xxs4-real": {
        "grid_ranks": 4,
        "real_tucker_ranks": [2, 50, 50, 50],
        "complex_tucker_ranks": False,
        "complex_grid_ranks": False,
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 4,
    },
    "xxs4-complex": {
        "grid_ranks": False,
        "real_tucker_ranks": False,
        "complex_tucker_ranks": [3, 40, 40, 40],
        "complex_grid_ranks": 4,
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 4,
    },
    "xxs4-tucker": {
        "grid_ranks": False,
        "real_tucker_ranks": [2, 50, 50, 50],
        "complex_tucker_ranks": [3, 40, 40, 40],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 4,
    },
    "xxs4-grid": {
        "grid_ranks": 3,
        "real_tucker_ranks": False,
        "complex_tucker_ranks": False,
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
        "num_segments": 4,
    },
}
