REFERENCES = {
    "xxs": {
        "grid_ranks": 1,
        "real_tucker_ranks": [2, 40, 40, 40],
        "complex_tucker_ranks": [2, 30, 30, 30],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
    },
    "xs": {
        "grid_ranks": 2,
        "real_tucker_ranks": [3, 50, 50, 50],
        "complex_tucker_ranks": [3, 40, 40, 40],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
    },
    "small": {
        "grid_ranks": 4,
        "real_tucker_ranks": [3, 75, 75, 60],
        "complex_tucker_ranks": [3, 60, 60, 40],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
    },
    "medium": {
        "grid_ranks": 8,
        "real_tucker_ranks": [3, 90, 90, 70],
        "complex_tucker_ranks": [3, 75, 75, 60],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
    },
    "large": {
        "grid_ranks": 16,
        "real_tucker_ranks": [4, 100, 100, 100],
        "complex_tucker_ranks": [4, 80, 80, 80],
        "conv_hidden": 48,
        "operator_steps": 1,
        "op_hdim": 48,
    },
}
